### ISSUE TITLE
Drop down button blocks the first digit in 'number of hours played'

### ISSUE THREAD

**Issue by shorty789** [tkashkin/eOSSteamSkin#6]
![screen shot 2018-06-25 at 23 51 49](https://user-images.githubusercontent.com/12603378/41879756-eb49202a-78d2-11e8-97e9-abe8e16d39fc.png)

I have attached a screenshot, the arrow to select either playing or streaming is out of place and blocks the first digit out of the number of hours played. This prevents me from using it as my main theme.

**Comment by tkashkin** [comment]
It can be fixed quite easily, but I'm not sure if it makes sense to do anything with this. This skin is very far from being done, it's very laggy (especially on Linux for some reason). Maybe it should be remade from scratch, but again, I'm not sure if it makes sense to do this, because Steam already started updating UI.

**Comment by tkashkin** [comment]
@shorty789 also do you know any existing skins with more or less same layout which can be used as a base?

**Comment by tkashkin** [comment]
New version is in [reborn branch](https://github.com/tkashkin/eOSSteamSkin/tree/reborn), right now it's not finished and somewhat works only on Linux. I'll add macOS support after I at least bring new version into similar state to old version.

**Comment by tkashkin** [comment]
New version is merged into master and all should work. Please report any new bugs you may encounter.
